
#file.dir= /home/ubuntu/nomargin/src/main/resources/static/data/

#file_dir : ${dir}



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 0
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      maxFileSize: 50MB

server:
  servlet:
    session:
      timeout: 300






